# OMB Python MPI Allgather Test
# Size (B)      Latency (us)
1                      39.51
2                      39.55
4                      39.57
8                      39.54
16                     39.50
32                     39.46
64                     39.75
128                    39.67
256                    70.53
512                    68.34
1024                  106.70
2048                   87.98
4096                   89.88
slurmstepd: error: *** STEP 12061115.35 ON nid005332 CANCELLED AT 2025-07-29T11:49:58 DUE TO TIME LIMIT ***
Abort(210835599) on node 2 (rank 2 in comm 0): Fatal error in internal_Allgather: Other MPI error, error stack:
internal_Allgather(2188).....................: MPI_Allgather(sendbuf=0x55f0d3294930, sendcount=8192, MPI_BYTE, recvbuf=0x55f0d2f94920, recvcount=8192, MPI_BYTE, MPI_COMM_WORLD) failed
MPID_Allgather(637)..........................: 
MPIDI_Allgather_allcomm_composition_json(578): 
MPIDI_Allgather_intra_composition_beta(1340).: 
MPIDI_NM_mpi_allgather(153)..................: 
MPIR_Allgather_impl(2216)....................: 
MPIR_Allgather_allcomm_auto(2136)............: 
MPIC_Sendrecv(306)...........................: 
MPIC_Wait(91)................................: 
MPIR_Wait(781)...............................: 
MPIR_Wait_state(738).........................: 
MPIDI_progress_test(134).....................: 
MPIDI_OFI_handle_cq_error(791)...............: OFI poll failed (ofi_events.c:793:MPIDI_OFI_handle_cq_error:Input/output error)
Traceback (most recent call last):
  File "/scratch/project_465001699/joachimsode/summer/BitBulldozersLab/mpi4py and cupy container using Cotainr/osu-micro-benchmarks-7.5.1/python/run.py", line 42, in <module>
    osu_allgather.osu_allgather(args=args)
  File "/scratch/project_465001699/joachimsode/summer/BitBulldozersLab/mpi4py and cupy container using Cotainr/osu-micro-benchmarks-7.5.1/python/mpi/collective/osu_allgather.py", line 54, in osu_allgather
